/* ============================================
   Icons — Centralized lucide-react icon exports
   Single source of truth for all UI icons
   ============================================ */

export {
    IndianRupee as IconINR,
    // Navigation & Layout
    BarChart3 as IconDashboard,
    BarChart3 as IconBarChart3,
    ClipboardList as IconOrders,
    ClipboardList as IconClipboardList,
    UtensilsCrossed as IconTables,
    UtensilsCrossed as IconUtensilsCrossed,
    FileText as IconMenu,
    Bell as IconBell,
    BellOff as IconBellOff,
    User as IconProfile,
    LogOut as IconLogout,
    Menu as IconHamburger,
    ArrowLeft as IconArrowLeft,
    ArrowRight as IconArrowRight,
    ChevronDown as IconChevronDown,
    X as IconClose,
    Plus as IconPlus,
    Minus as IconMinus,
    Check as IconCheck,
    Search as IconSearch,
    RefreshCw as IconRefresh,
    MoreHorizontal as IconMore,

    // Status & Actions
    Circle as IconStatusDot,
    CheckCircle as IconCheckCircle,
    AlertCircle as IconAlertCircle,
    Info as IconInfo,
    Trash2 as IconDelete,
    Edit3 as IconEdit,
    Copy as IconCopy,
    ExternalLink as IconExternalLink,

    // Restaurant specific
    ChefHat as IconChef,
    ShoppingCart as IconCart,
    CreditCard as IconCreditCard,
    Users as IconUsers,
    Calendar as IconCalendar,
    Clock as IconClock,
    Wrench as IconWrench,
    Accessibility as IconAccessible,
    Layers as IconBuffet,
    DollarSign as IconDollar,
    DollarSign as IconDollarSign,
    Smartphone as IconSmartphone,
    Rocket as IconRocket,
    Activity as IconActivity,
    PenTool as IconPenTool,
    TrendingUp as IconTrending,
    QrCode as IconQR,
    Phone as IconPhone,
    Star as IconStar,
    MapPin as IconMapPin,
    Home as IconHome,
    Settings as IconSettings,
    Package as IconPackage,
    Send as IconSend,
    Save as IconSave,
    Image as IconImage,
    Upload as IconUpload,
    Link as IconLink,
    ToggleLeft as IconToggle,
    Filter as IconFilter,
    Download as IconDownload,
    Printer as IconPrint,

    // Restaurant Details
    Wifi as IconWifi,
    Car as IconCar,
    Wine as IconWine,
    Heart as IconHeart,
    Share2 as IconShare,
    MessageSquare as IconMessageSquare,
    Map as IconMap,
    ShoppingBag as IconShoppingBag,
    CalendarDays as IconCalendarDays,
    Building as IconBuilding,
    ThumbsUp as IconThumbsUp,
    Quote as IconQuote,
} from 'lucide-react'